# Paralelizacion de entrenamiento de redes neuronales con TensorFlow

En esta seccion dejaremos atras los rudimentos de las matematicas y nos centraremos en utilizar TensorFlow, la cual es una de las librerias mas populares de arpendizaje profundo y que realiza una implementacion mas eficaz de las redes neuronales que cualquier otra implementacion de Numpy.

TensorFlow es una interfaz de programacion multiplataforma y escalable para implementar y ejecutar algortimos de aprendizaje automatico de una manera mas eficaz ya que permite usar tanto la CPU como la GPU, la cual suele tener muchos mas procesadores que la CPU, los cuales, combinando sus frecuencias, presentan un rendimiento mas potente. La API mas desarrollada de esta herramienta se presenta para Python, por lo cual muchos desarrolladores se ven atraidos a este lenguaje.

## Primeros pasos con TensorFlow

https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html


In [1]:
# Creando tensores
# =============================================
import tensorflow as tf
import numpy as np
np.set_printoptions(precision=3)

a = np.array([1, 2, 3], dtype=np.int32)
b = [4, 5, 6]

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [2]:
# Obteniendo las dimensiones de un tensor
# ===============================================
t_ones = tf.ones((2, 3))
print(t_ones)
t_ones.shape

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


TensorShape([2, 3])

In [3]:
# Obteniendo los valores del tensor como array
# ===============================================
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [4]:
# Creando un tensor de valores constantes
# ================================================
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)
print(const_tensor)

tf.Tensor([1.2   5.    3.142], shape=(3,), dtype=float32)


In [5]:
matriz = np.array([[2, 3, 4, 5], [6, 7, 8, 8]], dtype = np.int32)
matriz

array([[2, 3, 4, 5],
       [6, 7, 8, 8]])

In [6]:
matriz_tf = tf.convert_to_tensor(matriz)
print(matriz_tf, end = '\n'*2)
print(matriz_tf.numpy(), end = '\n'*2)
print(matriz_tf.shape)

tf.Tensor(
[[2 3 4 5]
 [6 7 8 8]], shape=(2, 4), dtype=int32)

[[2 3 4 5]
 [6 7 8 8]]

(2, 4)


## Manipulando los tipos de datos y forma de un tensor

In [7]:
# Cambiando el tipo de datos del tensor
# ==============================================
print(matriz_tf.dtype)

matriz_tf_n = tf.cast(matriz_tf, tf.int64)

print(matriz_tf_n.dtype)

<dtype: 'int32'>
<dtype: 'int64'>


In [8]:
# Transponiendo un tensor
# =================================================
t = tf.random.uniform(shape=(3, 5))
print(t, end = '\n'*2)

t_tr = tf.transpose(t)
print(t_tr, end = '\n'*2)

tf.Tensor(
[[0.558 0.107 0.675 0.764 0.455]
 [0.933 0.114 0.308 0.046 0.523]
 [0.577 0.128 0.518 0.53  0.791]], shape=(3, 5), dtype=float32)

tf.Tensor(
[[0.558 0.933 0.577]
 [0.107 0.114 0.128]
 [0.675 0.308 0.518]
 [0.764 0.046 0.53 ]
 [0.455 0.523 0.791]], shape=(5, 3), dtype=float32)



In [8]:
# Redimensionando un vector
# =====================================
t = tf.zeros((30,))
print(t, end = '\n'*2)
print(t.shape, end = '\n'*3)

t_reshape = tf.reshape(t, shape=(5, 6))
print(t_reshape, end = '\n'*2)
print(t_reshape.shape)

tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.], shape=(30,), dtype=float32)

(30,)


tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(5, 6), dtype=float32)

(5, 6)


In [9]:
# Removiendo las dimensiones innecesarias
# =====================================================
t = tf.zeros((1, 2, 1, 4, 1))
print(t, end = '\n'*2)
print(t.shape, end = '\n'*3)

t_sqz = tf.squeeze(t, axis=(2, 4))
print(t_sqz, end = '\n'*2)
print(t_sqz.shape, end = '\n'*3)
print(t.shape, ' --> ', t_sqz.shape)

tf.Tensor(
[[[[[0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]]]]], shape=(1, 2, 1, 4, 1), dtype=float32)

(1, 2, 1, 4, 1)


tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 2, 4), dtype=float32)

(1, 2, 4)


(1, 2, 1, 4, 1)  -->  (1, 2, 4)


## Operaciones matematicas sobre tensores

In [10]:
# Inicializando dos tensores con numeros aleatorios
# =============================================================
tf.random.set_seed(1)
t1 = tf.random.uniform(shape=(5, 2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5, 2), mean=0.0, stddev=1.0)

print(t1, '\n'*2, t2)

tf.Tensor(
[[-0.67   0.803]
 [ 0.262 -0.131]
 [-0.416  0.285]
 [ 0.952 -0.13 ]
 [ 0.32   0.21 ]], shape=(5, 2), dtype=float32) 

 tf.Tensor(
[[ 0.403 -1.088]
 [-0.063  1.337]
 [ 0.712 -0.489]
 [-0.764 -1.037]
 [-1.252  0.021]], shape=(5, 2), dtype=float32)


In [11]:
# Producto tipo element-wise: elemento a elemento
# =================================================
t3 = tf.multiply(t1, t2).numpy()
print(t3)

[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]


In [12]:
# Promedio segun el eje
# ================================================
t4 = tf.math.reduce_mean(t1, axis=None)
print(t4, end = '\n'*3)

t4 = tf.math.reduce_mean(t1, axis=0)
print(t4, end = '\n'*3)

t4 = tf.math.reduce_mean(t1, axis=1)
print(t4, end = '\n'*3)

tf.Tensor(0.14849123, shape=(), dtype=float32)


tf.Tensor([0.09  0.207], shape=(2,), dtype=float32)


tf.Tensor([ 0.067  0.066 -0.066  0.411  0.265], shape=(5,), dtype=float32)




In [13]:
# suma segun el eje
# =================================================
t4 = tf.math.reduce_sum(t1, axis=None)
print('Suma de todos los elementos:', t4, end = '\n'*3)

t4 = tf.math.reduce_sum(t1, axis=0)
print('Suma de los elementos por columnas:', t4, end = '\n'*3)

t4 = tf.math.reduce_sum(t1, axis=1)
print('Suma de los elementos por filas:', t4, end = '\n'*3)

Suma de todos los elementos: tf.Tensor(1.4849124, shape=(), dtype=float32)


Suma de los elementos por columnas: tf.Tensor([0.448 1.037], shape=(2,), dtype=float32)


Suma de los elementos por filas: tf.Tensor([ 0.133  0.131 -0.131  0.822  0.53 ], shape=(5,), dtype=float32)




In [14]:
# Desviacion estandar segun el eje
# =================================================
t4 = tf.math.reduce_std(t1, axis=None)
print('Suma de todos los elementos:', t4, end = '\n'*3)

t4 = tf.math.reduce_std(t1, axis=0)
print('Suma de los elementos por columnas:', t4, end = '\n'*3)

t4 = tf.math.reduce_std(t1, axis=1)
print('Suma de los elementos por filas:', t4, end = '\n'*3)

Suma de todos los elementos: tf.Tensor(0.4776839, shape=(), dtype=float32)


Suma de los elementos por columnas: tf.Tensor([0.576 0.343], shape=(2,), dtype=float32)


Suma de los elementos por filas: tf.Tensor([0.736 0.196 0.351 0.541 0.055], shape=(5,), dtype=float32)




In [15]:
# Producto entre matrices
# ===========================================
t5 = tf.linalg.matmul(t1, t2, transpose_b=True)
print(t5.numpy(), end = '\n'*2)

[[-1.144  1.115 -0.87  -0.321  0.856]
 [ 0.248 -0.191  0.25  -0.064 -0.331]
 [-0.478  0.407 -0.436  0.022  0.527]
 [ 0.525 -0.234  0.741 -0.593 -1.194]
 [-0.099  0.26   0.125 -0.462 -0.396]]



In [16]:
# Producto entre matrices
# ===========================================
t6 = tf.linalg.matmul(t1, t2, transpose_a=True)
print(t6.numpy())

[[-1.711  0.302]
 [ 0.371 -1.049]]


In [17]:
# Calculando la norma de un vector
# ==========================================
norm_t1 = tf.norm(t1, ord=2, axis=None).numpy()
print(norm_t1, end='\n'*2)

norm_t1 = tf.norm(t1, ord=2, axis=0).numpy()
print(norm_t1, end='\n'*2)

norm_t1 = tf.norm(t1, ord=2, axis=1).numpy()
print(norm_t1, end='\n'*2)

1.5818709

[1.303 0.897]

[1.046 0.293 0.504 0.96  0.383]



## Partir, apilar y concatenar tensores



In [18]:
# Datos a trabajar
# =======================================
tf.random.set_seed(1)
t = tf.random.uniform((6,))
print(t.numpy())

[0.165 0.901 0.631 0.435 0.292 0.643]


In [19]:
# Partiendo el tensor en un numero determinado de piezas
# ======================================================
t_splits = tf.split(t, num_or_size_splits = 3)
[item.numpy() for item in t_splits]

[array([0.165, 0.901], dtype=float32),
 array([0.631, 0.435], dtype=float32),
 array([0.292, 0.643], dtype=float32)]

In [20]:
# Partiendo el tensor segun los tamaños definidos
# ======================================================
tf.random.set_seed(1)
t = tf.random.uniform((6,))
print(t.numpy())
t_splits = tf.split(t, num_or_size_splits=[3, 3])
[item.numpy() for item in t_splits]

[0.165 0.901 0.631 0.435 0.292 0.643]


[array([0.165, 0.901, 0.631], dtype=float32),
 array([0.435, 0.292, 0.643], dtype=float32)]

In [21]:
print(matriz_tf.numpy())
# m_splits = tf.split(t, num_or_size_splits = 0, axis = 1)
matriz_n = tf.reshape(matriz_tf, shape = (8,))
print(matriz_n.numpy())
m_splits = tf.split(matriz_n, num_or_size_splits = 2)
[item.numpy() for item in m_splits]

[[2 3 4 5]
 [6 7 8 8]]
[2 3 4 5 6 7 8 8]


[array([2, 3, 4, 5]), array([6, 7, 8, 8])]

In [22]:
# Concatenando tensores
# =========================================
A = tf.ones((3,))
print(A, end ='\n'*2)

B = tf.zeros((2,))
print(B, end ='\n'*2)

C = tf.concat([A, B], axis=0)
print(C.numpy())

tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)

tf.Tensor([0. 0.], shape=(2,), dtype=float32)

[1. 1. 1. 0. 0.]


In [23]:
# Apilando tensores
# =========================================
A = tf.ones((3,))
print(A, end ='\n'*2)
B = tf.zeros((3,))
print(B, end ='\n'*2)
S = tf.stack([A, B], axis=1)
print(S.numpy())

tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)

[[1. 0.]
 [1. 0.]
 [1. 0.]]


Mas funciones y herramientas en:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf.

<div class="burk">
EJERCICIOS</div><i class="fa fa-lightbulb-o "></i>

1. Cree dos tensores de dimensiones (4, 6), de numeros aleatorios provenientes de una distribucion normal estandar con promedio 0.0 y dsv 1.0. Imprimalos.
2. Multiplique los anteriores tensores de las dos formas vistas, element-wise y producto matricial, realizando las dos transposiciones vistas. 
3. Calcule los promedios, desviaciones estandar y suma de sus elementos para los dos tensores.
4. Redimensione los tensores para que sean ahora de rango 1.
5. Calcule el coseno de los elementos de  los tensores (revise la documentacion).
6. Cree un tensor de rango 1 con 1001 elementos, empezando con el 0 y hasta el 30.
7. Realice un for sobre los elementos del tensor e imprimalos.
8. Realice el calculo de los factoriales de los numero del 1 al 30 usando el tensor del punto 6. Imprima el resultado como un DataFrame

In [25]:
#Cree dos tensores (4,6)
t1 = tf.random.normal(shape=(4, 6), mean=0.0, stddev=1.0)
t2 = tf.random.normal(shape=(4, 6), mean=0.0, stddev=1.0)
print(t1, '\n'*2, t2)

tf.Tensor(
[[ 0.403 -1.088 -0.063  1.337  0.712 -0.489]
 [-0.764 -1.037 -1.252  0.021 -0.551 -1.743]
 [-0.335 -1.043  1.009  1.236 -0.684  0.674]
 [-0.421 -1.041 -0.68   1.41  -0.477  2.047]], shape=(4, 6), dtype=float32) 

 tf.Tensor(
[[-0.457 -0.407  0.729 -0.893  0.313  0.994]
 [-1.784 -0.522  0.981 -0.676  1.146  0.206]
 [-0.197  0.538  0.764 -0.836  0.336  1.56 ]
 [ 0.723  1.075 -0.266  0.012 -0.188 -0.87 ]], shape=(4, 6), dtype=float32)


In [26]:
#multiplique los tensores
# Producto tipo element-wise: elemento a elemento
# =================================================
t3 = tf.multiply(t1, t2).numpy()
print(t3)

[[-0.184  0.443 -0.046 -1.194  0.223 -0.486]
 [ 1.364  0.541 -1.228 -0.014 -0.632 -0.359]
 [ 0.066 -0.561  0.771 -1.034 -0.23   1.051]
 [-0.304 -1.12   0.181  0.016  0.09  -1.782]]


In [27]:
# Producto entre matrices
# ===========================================
t5 = tf.linalg.matmul(t1, t2, transpose_b=True)
print(t5.numpy(), end = '\n'*2)

[[-1.245 -0.402 -2.355 -0.555]
 [-2.065 -0.328 -4.287  0.286]
 [ 0.665  0.652  0.064 -2.075]
 [ 0.748 -0.45   0.858 -2.918]]



In [28]:
#Calcule los promedios, desviaciones estandar y suma de sus elementos para los dos tensores.
# Promedio segun el eje
# ================================================
t4 = tf.math.reduce_mean(t1, axis=None)
print(t4, end = '\n'*3)

t4 = tf.math.reduce_mean(t1, axis=0)
print(t4, end = '\n'*3)

t4 = tf.math.reduce_mean(t1, axis=1)
print(t4, end = '\n'*3)

tf.Tensor(-0.11752671, shape=(), dtype=float32)


tf.Tensor([-0.279 -1.052 -0.246  1.001 -0.25   0.122], shape=(6,), dtype=float32)


tf.Tensor([ 0.135 -0.888  0.143  0.14 ], shape=(4,), dtype=float32)




In [29]:
# suma segun el eje
# =================================================
t4 = tf.math.reduce_sum(t1, axis=None)
print('Suma de todos los elementos:', t4, end = '\n'*3)

t4 = tf.math.reduce_sum(t1, axis=0)
print('Suma de los elementos por columnas:', t4, end = '\n'*3)

t4 = tf.math.reduce_sum(t1, axis=1)
print('Suma de los elementos por filas:', t4, end = '\n'*3)

Suma de todos los elementos: tf.Tensor(-2.820641, shape=(), dtype=float32)


Suma de los elementos por columnas: tf.Tensor([-1.117 -4.209 -0.986  4.004 -1.001  0.488], shape=(6,), dtype=float32)


Suma de los elementos por filas: tf.Tensor([ 0.811 -5.327  0.857  0.838], shape=(4,), dtype=float32)




In [30]:
# Desviacion estandar segun el eje
# =================================================
t4 = tf.math.reduce_std(t1, axis=None)
print('Suma de todos los elementos:', t4, end = '\n'*3)

t4 = tf.math.reduce_std(t1, axis=0)
print('Suma de los elementos por columnas:', t4, end = '\n'*3)

t4 = tf.math.reduce_std(t1, axis=1)
print('Suma de los elementos por filas:', t4, end = '\n'*3)

Suma de todos los elementos: tf.Tensor(0.97720635, shape=(), dtype=float32)


Suma de los elementos por columnas: tf.Tensor([0.425 0.021 0.838 0.569 0.56  1.402], shape=(6,), dtype=float32)


Suma de los elementos por filas: tf.Tensor([0.793 0.554 0.87  1.156], shape=(4,), dtype=float32)




In [40]:
#Redimensione los tensores para que sean ahora de rango 1.
t_reshape = tf.reshape(t1, shape=(24,))
print(t_reshape, end = '\n'*2)
print(t_reshape.shape)

tf.Tensor(
[ 0.403 -1.088 -0.063  1.337  0.712 -0.489 -0.764 -1.037 -1.252  0.021
 -0.551 -1.743 -0.335 -1.043  1.009  1.236 -0.684  0.674 -0.421 -1.041
 -0.68   1.41  -0.477  2.047], shape=(24,), dtype=float32)

(24,)


In [41]:
#Calcule el coseno de los elementos de los tensores (revise la documentacion).
tf1cos=tf.math.cos(t1, name=None)
tf2cos=tf.math.cos(t2, name=None)
print(tf1cos)
print(tf2cos)

tf.Tensor(
[[ 0.92   0.464  0.998  0.232  0.757  0.883]
 [ 0.722  0.509  0.313  1.     0.852 -0.172]
 [ 0.944  0.504  0.533  0.328  0.775  0.782]
 [ 0.913  0.505  0.778  0.161  0.888 -0.459]], shape=(4, 6), dtype=float32)
tf.Tensor(
[[ 0.897  0.918  0.746  0.627  0.952  0.545]
 [-0.212  0.867  0.556  0.78   0.412  0.979]
 [ 0.981  0.859  0.722  0.67   0.944  0.011]
 [ 0.75   0.475  0.965  1.     0.982  0.645]], shape=(4, 6), dtype=float32)


In [49]:
#Cree un tensor de rango 1 con 1001 elementos, empezando con el 0 y hasta el 30.
tfrand=tf.range(0, 30, 0.03)
tfrand

<tf.Tensor: shape=(1000,), dtype=float32, numpy=
array([ 0.  ,  0.03,  0.06,  0.09,  0.12,  0.15,  0.18,  0.21,  0.24,
        0.27,  0.3 ,  0.33,  0.36,  0.39,  0.42,  0.45,  0.48,  0.51,
        0.54,  0.57,  0.6 ,  0.63,  0.66,  0.69,  0.72,  0.75,  0.78,
        0.81,  0.84,  0.87,  0.9 ,  0.93,  0.96,  0.99,  1.02,  1.05,
        1.08,  1.11,  1.14,  1.17,  1.2 ,  1.23,  1.26,  1.29,  1.32,
        1.35,  1.38,  1.41,  1.44,  1.47,  1.5 ,  1.53,  1.56,  1.59,
        1.62,  1.65,  1.68,  1.71,  1.74,  1.77,  1.8 ,  1.83,  1.86,
        1.89,  1.92,  1.95,  1.98,  2.01,  2.04,  2.07,  2.1 ,  2.13,
        2.16,  2.19,  2.22,  2.25,  2.28,  2.31,  2.34,  2.37,  2.4 ,
        2.43,  2.46,  2.49,  2.52,  2.55,  2.58,  2.61,  2.64,  2.67,
        2.7 ,  2.73,  2.76,  2.79,  2.82,  2.85,  2.88,  2.91,  2.94,
        2.97,  3.  ,  3.03,  3.06,  3.09,  3.12,  3.15,  3.18,  3.21,
        3.24,  3.27,  3.3 ,  3.33,  3.36,  3.39,  3.42,  3.45,  3.48,
        3.51,  3.54,  3.57,  3.6 ,  3.63,

In [50]:
#Realice un for sobre los elementos del tensor e imprimalos.
for n in tfrand:
    print(n)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.03, shape=(), dtype=float32)
tf.Tensor(0.06, shape=(), dtype=float32)
tf.Tensor(0.089999996, shape=(), dtype=float32)
tf.Tensor(0.12, shape=(), dtype=float32)
tf.Tensor(0.14999999, shape=(), dtype=float32)
tf.Tensor(0.17999999, shape=(), dtype=float32)
tf.Tensor(0.21, shape=(), dtype=float32)
tf.Tensor(0.24, shape=(), dtype=float32)
tf.Tensor(0.26999998, shape=(), dtype=float32)
tf.Tensor(0.29999998, shape=(), dtype=float32)
tf.Tensor(0.32999998, shape=(), dtype=float32)
tf.Tensor(0.35999998, shape=(), dtype=float32)
tf.Tensor(0.39, shape=(), dtype=float32)
tf.Tensor(0.42, shape=(), dtype=float32)
tf.Tensor(0.45, shape=(), dtype=float32)
tf.Tensor(0.48, shape=(), dtype=float32)
tf.Tensor(0.51, shape=(), dtype=float32)
tf.Tensor(0.53999996, shape=(), dtype=float32)
tf.Tensor(0.56999993, shape=(), dtype=float32)
tf.Tensor(0.5999999, shape=(), dtype=float32)
tf.Tensor(0.6299999, shape=(), dtype=float32)
tf.Tensor(0.65999985, shape=(), dt

tf.Tensor(8.310021, shape=(), dtype=float32)
tf.Tensor(8.340021, shape=(), dtype=float32)
tf.Tensor(8.370021, shape=(), dtype=float32)
tf.Tensor(8.400021, shape=(), dtype=float32)
tf.Tensor(8.43002, shape=(), dtype=float32)
tf.Tensor(8.46002, shape=(), dtype=float32)
tf.Tensor(8.49002, shape=(), dtype=float32)
tf.Tensor(8.52002, shape=(), dtype=float32)
tf.Tensor(8.550019, shape=(), dtype=float32)
tf.Tensor(8.580019, shape=(), dtype=float32)
tf.Tensor(8.610019, shape=(), dtype=float32)
tf.Tensor(8.640018, shape=(), dtype=float32)
tf.Tensor(8.670018, shape=(), dtype=float32)
tf.Tensor(8.700018, shape=(), dtype=float32)
tf.Tensor(8.730018, shape=(), dtype=float32)
tf.Tensor(8.760017, shape=(), dtype=float32)
tf.Tensor(8.790017, shape=(), dtype=float32)
tf.Tensor(8.820017, shape=(), dtype=float32)
tf.Tensor(8.850017, shape=(), dtype=float32)
tf.Tensor(8.880016, shape=(), dtype=float32)
tf.Tensor(8.910016, shape=(), dtype=float32)
tf.Tensor(8.940016, shape=(), dtype=float32)
tf.Tensor(8.97

tf.Tensor(15.959953, shape=(), dtype=float32)
tf.Tensor(15.989953, shape=(), dtype=float32)
tf.Tensor(16.019953, shape=(), dtype=float32)
tf.Tensor(16.049953, shape=(), dtype=float32)
tf.Tensor(16.079954, shape=(), dtype=float32)
tf.Tensor(16.109955, shape=(), dtype=float32)
tf.Tensor(16.139956, shape=(), dtype=float32)
tf.Tensor(16.169956, shape=(), dtype=float32)
tf.Tensor(16.199957, shape=(), dtype=float32)
tf.Tensor(16.229958, shape=(), dtype=float32)
tf.Tensor(16.259958, shape=(), dtype=float32)
tf.Tensor(16.289959, shape=(), dtype=float32)
tf.Tensor(16.31996, shape=(), dtype=float32)
tf.Tensor(16.34996, shape=(), dtype=float32)
tf.Tensor(16.379961, shape=(), dtype=float32)
tf.Tensor(16.409962, shape=(), dtype=float32)
tf.Tensor(16.439962, shape=(), dtype=float32)
tf.Tensor(16.469963, shape=(), dtype=float32)
tf.Tensor(16.499964, shape=(), dtype=float32)
tf.Tensor(16.529964, shape=(), dtype=float32)
tf.Tensor(16.559965, shape=(), dtype=float32)
tf.Tensor(16.589966, shape=(), dtype

tf.Tensor(24.420145, shape=(), dtype=float32)
tf.Tensor(24.450146, shape=(), dtype=float32)
tf.Tensor(24.480146, shape=(), dtype=float32)
tf.Tensor(24.510147, shape=(), dtype=float32)
tf.Tensor(24.540148, shape=(), dtype=float32)
tf.Tensor(24.570148, shape=(), dtype=float32)
tf.Tensor(24.60015, shape=(), dtype=float32)
tf.Tensor(24.63015, shape=(), dtype=float32)
tf.Tensor(24.66015, shape=(), dtype=float32)
tf.Tensor(24.690151, shape=(), dtype=float32)
tf.Tensor(24.720152, shape=(), dtype=float32)
tf.Tensor(24.750153, shape=(), dtype=float32)
tf.Tensor(24.780153, shape=(), dtype=float32)
tf.Tensor(24.810154, shape=(), dtype=float32)
tf.Tensor(24.840155, shape=(), dtype=float32)
tf.Tensor(24.870155, shape=(), dtype=float32)
tf.Tensor(24.900156, shape=(), dtype=float32)
tf.Tensor(24.930157, shape=(), dtype=float32)
tf.Tensor(24.960157, shape=(), dtype=float32)
tf.Tensor(24.990158, shape=(), dtype=float32)
tf.Tensor(25.020159, shape=(), dtype=float32)
tf.Tensor(25.05016, shape=(), dtype=f

In [57]:
#Realice el calculo de los factoriales de los numero del 1 al 30 usando el tensor del punto 6. Imprima el resultado como un DataFrame
import pandas as pd    
import numpy as np  
from math import factorial
from scipy.special import factorial
t=tfrand.numpy()
fact=factorial(t, exact=False)
data=pd.DataFrame(fact)
data

0
0    1.000000e+00
1    9.835500e-01
2    9.687436e-01
3    9.554595e-01
4    9.435902e-01
..            ...
995  1.590640e+32
996  1.762158e+32
997  1.952228e+32
998  2.162864e+32
999  2.396297e+32

[1000 rows x 1 columns]

# Creación de *pipelines* de entrada con tf.data: la API de conjunto de datos de TensorFlow

Cuando entrenamos un modelo NN profundo, generalmente entrenamos el modelo de forma incremental utilizando un algoritmo de optimización iterativo como el descenso de gradiente estocástico, como hemos visto en clases anteriores.

La API de Keras es un contenedor de TensorFlow para crear modelos NN. La API de Keras proporciona un método, `.fit ()`, para entrenar los modelos. En los casos en que el conjunto de datos de entrenamiento es bastante pequeño y se puede cargar como un tensor en la memoria, los modelos de TensorFlow (que se compilan con la API de Keras) pueden usar este tensor directamente a través de su método .fit () para el entrenamiento. Sin embargo, en casos de uso típicos, cuando el conjunto de datos es demasiado grande para caber en la memoria de la computadora, necesitaremos cargar los datos del dispositivo de almacenamiento principal (por ejemplo, el disco duro o la unidad de estado sólido) en trozos, es decir, lote por lote. 

Además, es posible que necesitemos construir un *pipeline* de procesamiento de datos para aplicar ciertas transformaciones y pasos de preprocesamiento a nuestros datos, como el centrado medio, el escalado o la adición de ruido para aumentar el procedimiento de entrenamiento y evitar el sobreajuste.

Aplicar las funciones de preprocesamiento manualmente cada vez puede resultar bastante engorroso. Afortunadamente, TensorFlow proporciona una clase especial para construir *pipelines* de preprocesamiento eficientes y convenientes. En esta parte, veremos una descripción general de los diferentes métodos para construir un conjunto de datos de TensorFlow, incluidas las transformaciones del conjunto de datos y los pasos de preprocesamiento comunes.

## Creando un Dataset de TensorFlow desde tensores existentes

Si los datos ya existen en forma de un objeto tensor, una lista de Python o una matriz NumPy, podemos crear fácilmente un conjunto de datos usando la función `tf.data.Dataset.from_tensor_ slices()`. Esta función devuelve un objeto de la clase Dataset, que podemos usar para iterar a través de los elementos individuales en el conjunto de datos de entrada:


In [ ]:
# Ejemplo con listas
# ======================================================
a = [1.2, 3.4, 7.5, 4.1, 5.0, 1.0]
ds = tf.data.Dataset.from_tensor_slices(a)
print(ds)

In [ ]:
for item in ds:
    print(item)

Si queremos crear lotes a partir de este conjunto de datos, con un tamaño de lote deseado de 3, podemos hacerlo de la siguiente manera:

In [ ]:
# Creando lotes de 3 elementos cada uno
# ===================================================
ds_batch = ds.batch(3)
for i, elem in enumerate(ds_batch, 1):
    print(f'batch {i}:', elem.numpy())

Esto creará dos lotes a partir de este conjunto de datos, donde los primeros tres elementos van al lote n° 1 y los elementos restantes al lote n° 2. El método `.batch()` tiene un argumento opcional, `drop_remainder`, que es útil para los casos en los que el número de elementos en el tensor no es divisible por el tamaño de lote deseado. El valor predeterminado de `drop_remainder` es `False`.

## Combinar dos tensores en un Dataset

A menudo, podemos tener los datos en dos (o posiblemente más) tensores. Por ejemplo, podríamos tener un tensor para características y un tensor para etiquetas. En tales casos, necesitamos construir un conjunto de datos que combine estos tensores juntos, lo que nos permitirá recuperar los elementos de estos tensores en tuplas.

Suponga que tenemos dos tensores, t_x y t_y. El tensor t_x contiene nuestros valores de características, cada uno de tamaño 3, y t_y almacena las etiquetas de clase. Para este ejemplo, primero creamos estos dos tensores de la siguiente manera:

In [ ]:
# Datos de ejemplo
# ============================================
tf.random.set_seed(1)
t_x = tf.random.uniform([4, 3], dtype=tf.float32)
t_y = tf.range(4)
print(t_x)
print(t_y)

In [ ]:
# Uniendo los dos tensores en un Dataset
# ============================================
ds_x = tf.data.Dataset.from_tensor_slices(t_x)
ds_y = tf.data.Dataset.from_tensor_slices(t_y)

ds_joint = tf.data.Dataset.zip((ds_x, ds_y))

for example in ds_joint:
    print('x:', example[0].numpy(),' y:', example[1].numpy())

In [ ]:
ds_joint = tf.data.Dataset.from_tensor_slices((t_x, t_y))
for example in ds_joint:
    #print(example)
    print('x:', example[0].numpy(), ' y:', example[1].numpy())


In [ ]:
# Operacion sobre el dataset generado
# ====================================================
ds_trans = ds_joint.map(lambda x, y: (x*2-1.0, y))
for example in ds_trans: 
    print(' x:', example[0].numpy(), ' y:', example[1].numpy())

## Mezclar, agrupar y repetir

Para entrenar un modelo NN usando la optimización de descenso de gradiente estocástico, es importante alimentar los datos de entrenamiento como lotes mezclados aleatoriamente. Ya hemos visto arriba como crear lotes llamando al método `.batch()` de un objeto de conjunto de datos. Ahora, además de crear lotes, vamos a mezclar y reiterar sobre los conjuntos de datos:

In [ ]:
# Mezclando los elementos de un tensor
# ===================================================
tf.random.set_seed(1)
ds = ds_joint.shuffle(buffer_size = len(t_x))
for example in ds:
    print(' x:', example[0].numpy(), ' y:', example[1].numpy())

donde las filas se barajan sin perder la correspondencia uno a uno entre las entradas en x e y. El método `.shuffle()` requiere un argumento llamado `buffer_size`, que determina cuántos elementos del conjunto de datos se agrupan antes de barajar. Los elementos del búfer se recuperan aleatoriamente y su lugar en el búfer se asigna a los siguientes elementos del conjunto de datos original (sin mezclar). Por lo tanto, si elegimos un tamaño de búfer pequeño, es posible que no mezclemos perfectamente el conjunto de datos.

Si el conjunto de datos es pequeño, la elección de un tamaño de búfer relativamente pequeño puede afectar negativamente el rendimiento predictivo del NN, ya que es posible que el conjunto de datos no esté completamente aleatorizado. En la práctica, sin embargo, por lo general no tiene un efecto notable cuando se trabaja con conjuntos de datos relativamente grandes, lo cual es común en el aprendizaje profundo.

Alternativamente, para asegurar una aleatorización completa durante cada época, simplemente podemos elegir un tamaño de búfer que sea igual al número de ejemplos de entrenamiento, como en el código anterior (`buffer_size = len(t_x)`).

 Ahora, creemos lotes a partir del conjunto de datos ds_joint:

In [ ]:
ds = ds_joint.batch(batch_size = 3, drop_remainder = False)
print(ds)
batch_x, batch_y = next(iter(ds))
print('Batch-x:\n', batch_x.numpy())

In [ ]:
print('Batch-y: ', batch_y.numpy())

Además, al entrenar un modelo para múltiples épocas, necesitamos mezclar e iterar sobre el conjunto de datos por el número deseado de épocas. Entonces, repitamos el conjunto de datos por lotes dos veces:

In [ ]:
ds = ds_joint.batch(3).repeat(count = 2)
for i,(batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.numpy(), batch_y.numpy(), end = '\n'*2)

Esto da como resultado dos copias de cada lote. Si cambiamos el orden de estas dos operaciones, es decir, primero lote y luego repetimos, los resultados serán diferentes:

In [ ]:
ds = ds_joint.repeat(count=2).batch(3)
for i,(batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.numpy(), batch_y.numpy(), end = '\n'*2)